# 案例：癌症分类预测
- 获取数据 数据描述
    - 加上names
- 数据处理
    - 处理缺失值 
- 数据集划分
- 特征工程:
    - 无量纲化处理-标准化
- 逻辑回归预估器
- 模型评估

In [1]:
import pandas as pd
import numpy as np

## 获取数据 数据描述
    - 699条样本，共11列数据，第一列用于检索的id，后9列分别是与肿瘤相关的医学特征，最后一列表示肿瘤类型的数值
    - 包含16个缺失值，用'?'标出

In [68]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path,names=column_name)
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

## 数据处理
- 替换成np.ana
- 删除缺失样本

In [43]:
#替换成np.ana
data = data.replace(to_replace='?',value=np.nan)
#删除缺失样本
data.dropna(inplace=True)

In [44]:
#说明不存在缺失值了
data.isnull().any()

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

## 数据集划分
    - 删选特征值和目标值

In [45]:
from sklearn.model_selection import train_test_split
x = data.iloc[:,1:-1]
y = data['Class']

In [46]:
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [47]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [48]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

- 特征工程:
    - 无量纲化处理-标准化


In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [55]:
x_train

array([[-0.86771574, -0.69903168, -0.73271171, ..., -0.19214052,
        -0.59736623, -0.34772638],
       [-1.21975256, -0.69903168, -0.73271171, ..., -0.19214052,
        -0.59736623, -0.34772638],
       [ 0.54043152, -0.37454916, -0.06220519, ..., -0.99850073,
        -0.59736623, -0.34772638],
       ..., 
       [ 1.94857877,  2.221311  ,  2.28456761, ...,  0.21103959,
         2.4143007 ,  4.61302643],
       [-0.51567893, -0.69903168, -0.73271171, ..., -0.59532062,
         0.07189309, -0.34772638],
       [ 0.1883947 , -0.69903168, -0.73271171, ..., -0.59532062,
        -0.59736623, -0.34772638]])

## 逻辑回归预估器


In [56]:
from sklearn.linear_model import LogisticRegression

In [63]:
estimator = LogisticRegression()
estimator.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [64]:
# 逻辑回归的模型参数
# 回归系数和偏置
estimator.coef_

array([[ 1.46676366,  0.06158949,  0.70641306,  1.27959524,  0.04022096,
         1.47232708,  0.97181639,  0.93234226,  1.11635269]])

In [65]:
estimator.intercept_

array([-0.57244639])

## 模型评估

In [66]:
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

y_predict:
 [2 2 2 2 2 4 2 4 2 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2 4 4 4 2 4 2 4 2 4 2
 4 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 4 2 2 2 2 2 2 4 2 4 2 4 2 4 4 2 2 2 2 2 2
 2 2 4 2 4 2 2 2 2 2 4 2 4 2 4 2 4 2 4 2 2 4 4 2 2 2 4 2 2 4 2 4 4 2 4 2 4
 2 4 2 4 4 2 4 4 4 2 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 4 4 2 4 2 4 2 4 2 2 4 2
 2 4 2 2 2 2 4 2 2 4 4 2 2 2 4 4 2 4 2 2 4 4 2]
直接比对真实值和预测值:
 398     True
258     True
555     True
624     True
685     True
283     True
150     True
25      True
424     True
245     True
384     True
218     True
75      True
232    False
649     True
493     True
490     True
310     True
70      True
410     True
369     True
52      True
388     True
102     True
583     True
163     True
676     True
670     True
465     True
316     True
       ...  
571     True
673     True
588     True
405     True
4       True
32      True
478     True
473     True
87      True
495     True
243     True
695     True
408     True
288     True
265     True
278     True
236     True
15