# 癌症分类预测
### 逻辑回归
- 获取数据 数据描述
    - 加上names
- 数据处理
    - 处理缺失值 
- 数据集划分
- 特征工程:
    - 无量纲化处理-标准化
- 逻辑回归预估器
- 模型评估
- 查看精确率，召回率，F1-score
- 计算AUC

## 1获取数据 数据描述
    - 699条样本，共11列数据，第一列用于检索的id，后9列分别是与肿瘤相关的医学特征，最后一列表示肿瘤类型的数值
    - 包含16个缺失值，用'?'标出

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path,names=column_name)
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

## 2数据处理
- 替换成np.ana
- 删除缺失样本

In [3]:
#替换成np.ana
data = data.replace(to_replace='?',value=np.nan)
#删除缺失样本
data.dropna(inplace=True)

In [4]:
#说明不存在缺失值了
data.isnull().any()

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

## 3数据集划分
- 删选特征值和目标值

In [5]:
## -1不包括最后一列
from sklearn.model_selection import train_test_split
x = data.iloc[:,1:-1]
y = data['Class']

In [6]:
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [7]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

## 4特征工程:
- 无量纲化处理-标准化

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [11]:
x_train

array([[ -5.06438736e-01,  -7.18688063e-01,  -7.62415227e-01, ...,
         -6.18439689e-01,  -1.85271933e-03,  -3.64995699e-01],
       [ -5.06438736e-01,  -7.18688063e-01,  -7.62415227e-01, ...,
         -2.17628144e-01,  -6.34247583e-01,  -3.64995699e-01],
       [ -1.21200780e+00,  -7.18688063e-01,  -7.62415227e-01, ...,
         -2.17628144e-01,  -6.34247583e-01,  -3.64995699e-01],
       ..., 
       [ -1.53654201e-01,  -7.18688063e-01,  -7.62415227e-01, ...,
         -6.18439689e-01,  -6.34247583e-01,  -3.64995699e-01],
       [  1.99130333e-01,  -8.69828471e-02,   2.21677032e-01, ...,
          1.83183401e-01,   1.89533187e+00,  -3.64995699e-01],
       [  1.25748394e+00,  -8.69828471e-02,   5.49707786e-01, ...,
         -1.01925123e+00,   9.46739575e-01,   1.72009467e-01]])

## 5逻辑回归预估器

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
estimator = LogisticRegression()
estimator.fit(x_train,y_train)
## 默认迭代100次

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
# 逻辑回归的模型参数
# 回归系数和偏置
estimator.coef_

array([[ 1.08887409,  0.3061914 ,  0.86266568,  0.78848389,  0.10142429,
         1.11340256,  0.98072839,  0.74533151,  0.95513835]])

In [15]:
estimator.intercept_

array([-1.06695745])

## 6模型评估

In [16]:
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

y_predict:
 [2 2 4 4 4 2 2 2 2 2 2 4 2 2 2 2 2 4 2 2 2 2 2 4 2 2 2 2 4 4 2 4 2 2 2 2 4
 2 2 2 2 2 2 4 4 2 4 2 2 2 2 4 2 4 4 4 2 2 4 2 4 4 2 2 2 4 2 4 2 2 2 2 2 2
 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 4 4 2 2 4 2 2 4 2 2 4 2 2 2 4 4 4
 4 2 2 2 4 2 4 4 4 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2 2 2 4 2 4 2 2 2 4 2 2 2 4
 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 4 4]
直接比对真实值和预测值:
 43     False
596     True
49      True
330     True
425     True
547     True
584     True
273    False
689     True
322     True
625     True
239     True
664     True
48      True
405     True
537     True
528     True
416     True
51     False
419     True
119     True
392     True
88      True
255     True
640     True
101    False
154     True
390     True
340     True
104     True
       ...  
486     True
404     True
391     True
490     True
281     True
28      True
605     True
415     True
304     True
298     True
659     True
683     True
22      True
461     True
663     True
332     True
642     True
27

## 7查看精确率，召回率，F1-score

In [17]:
from sklearn.metrics import classification_report

In [18]:
report = classification_report(y_test,y_predict,labels=[2,4],target_names=['良性','恶性'])

In [19]:
print(report) 
## 一共有171个样本，其中良性115，恶性56个
## 恶性精确率 98%，召回率86%，f1-score91%
## 事实上有100个恶性肿瘤，只有86个被查出来

             precision    recall  f1-score   support

         良性       0.93      0.99      0.96       115
         恶性       0.98      0.86      0.91        56

avg / total       0.95      0.95      0.95       171



## 8计算AUC

In [20]:
# y_true:每个样本的真实类别，必须为0(反例)，1(正例)
# 转换y_test
y_test.head()

43     4
596    2
49     4
330    4
425    4
Name: Class, dtype: int64

In [21]:
y_true = np.where(y_test>3,1,0)

In [26]:
y_true

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1])

In [27]:
y_predict

array([2, 2, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2,
       4, 2, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       4, 2, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2,
       2, 2, 4, 4, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 2, 2, 4, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4,
       2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 2, 2, 2, 2, 2, 4, 4], dtype=int64)

In [23]:
from sklearn.metrics import roc_auc_score

In [24]:
roc_auc_score(y_true,y_predict)

0.92422360248447211